name: Foo Action

on: [push, pull_request]

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pwd
      - run: date
      - name: Show hostname
        run: echo $HOSTNAME
      - name: Show workspace
        run: echo $GITHUB_WORKSPACE
      - run: git fetch origin main
      - run: git status
      - run: git branch -v
      - run: git remote -v
      - run: git diff --name-only origin/main