name: Foo Action

on: [push, pull_request]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          date
          echo $HOSTNAME
          echo $GITHUB_TOKEN
          ls -alp
          git status
          git branch -v