name: Foo Action

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -al
      - run: date
      - name: Show hostname
        run: echo $HOSTNAME
      - name: Show workspace
        run: echo $GITHUB_WORKSPACE
      - name: Git info
        run: git status