name: Foo Action

on: [push, pull_request]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date
          echo $HOSTNAME
          whoami
          ls -alp
      - name: modify file
        run: |
          cat README.md
          sed -i 's/playing/messing/' README.md
          cat README.md 
