name: Release Action Test

on:
  release:
    types: [published]

jobs:
  release-job:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date
          echo $HOSTNAME
          whoami
          ls -alp
          echo "** Release Action Test **"