name: Release Action Test

on: push

jobs:
  release-job:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: ls -alp > out.txt
      - name: Test
        run: cat out.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out.txt