name: Release Action Test

on:
  release:
    types: [published]

jobs:
  release-job:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: ls -alp > out.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out.txt