name: Schedule Action

on:
  schedule:
    - cron: '40 0 * * *'

jobs:
  schedule-test:
    name: Schedule Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run script
        run: python3 foo.py